### ISSUE TITLE
Fix wierd date

### ISSUE THREAD

**Issue by soberich** [arrow-kt/arrow-playground#16]
You guys are way beyond your time!

![image](https://user-images.githubusercontent.com/25544967/56027897-3ec15780-5d17-11e9-98c8-eab22705408a.png)

Today is 12 Apr 2019. But you article written 2 days after today.
What is it you don't tell the world about functional programming paradox?

**Comment by calvellido** [comment]
Thanks for pointing it out @soberich!

This has been now fixed: https://www.47deg.com/blog/arrow-playground/
